# Generated by Django 5.1 on 2024-09-16 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_worksample'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='otherexamples')),
                ('title', models.CharField(max_length=200)),
                ('des', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('time', models.CharField(max_length=200)),
                ('tools', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('pagecount', models.IntegerField()),
                ('otherexamples', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cv_examples', to='app.otherexample')),
            ],
        ),
    ]
