# Generated by Django 5.1 on 2024-09-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_otherexample_language_otherexample_pagecount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherexample',
            name='generaldes',
            field=models.TextField(null=True),
        ),
    ]
