# Generated by Django 5.1 on 2024-09-16 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_otherexample_generaldes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherexample',
            old_name='generaldes',
            new_name='generalـdes',
        ),
    ]
