# Generated by Django 5.1 on 2024-09-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_generaldes_otherexample_generalـdes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherexample',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
