# Generated by Django 5.1 on 2024-09-22 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_otherexample_image_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_mobile', models.ImageField(null=True, upload_to='otherexamples/mobile')),
                ('other_example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_images', to='app.otherexample')),
            ],
        ),
    ]
