# Generated by Django 5.1 on 2024-09-22 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_image_mobile_mobileimage_image_mobile1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='sliders')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='sliders')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='sliders')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='sliders')),
                ('other_example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_sliders', to='app.otherexample')),
            ],
        ),
    ]
