# Generated by Django 5.1 on 2024-09-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_imagebig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageBig',
        ),
    ]
