# Generated by Django 5.1.1 on 2024-09-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_imagebig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileimage',
            name='image_mobile2',
            field=models.ImageField(blank=True, null=True, upload_to='otherexamples/mobile'),
        ),
        migrations.AlterField(
            model_name='mobileimage',
            name='image_mobile3',
            field=models.ImageField(blank=True, null=True, upload_to='otherexamples/mobile'),
        ),
        migrations.AlterField(
            model_name='mobileimage',
            name='image_mobile4',
            field=models.ImageField(blank=True, null=True, upload_to='otherexamples/mobile'),
        ),
    ]
