# Generated by Django 5.1.1 on 2024-09-24 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_mobileimage_image_mobile2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MobileImage',
        ),
    ]
