# Generated by Django 5.1.1 on 2024-09-24 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_imageotherexample_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageotherexample',
            name='otherExample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_images', to='app.otherexample'),
        ),
        migrations.CreateModel(
            name='ImageOtherExampleMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='otherExampleImages')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='otherExampleImages')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='otherExampleImages')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='otherExampleImages')),
                ('otherExample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_images', to='app.otherexample')),
            ],
        ),
    ]
