# Generated by Django 4.2.10 on 2024-09-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_imageotherexample_otherexample_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='imageContent',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/content'),
        ),
    ]
