# Generated by Django 5.1 on 2024-09-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_otherexample_created_otherexample_popularity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherexample',
            name='language',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='otherexample',
            name='pagecount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='otherexample',
            name='time',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='otherexample',
            name='tools',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='otherexample',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
