# Generated by Django 5.1 on 2024-09-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_otherexample_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherexample',
            name='image_mobile',
            field=models.ImageField(null=True, upload_to='otherexamples'),
        ),
    ]
