# Generated by Django 5.1.1 on 2024-09-24 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_mobileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageOtherExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='otherExampleImages')),
                ('otherExample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.otherexample')),
            ],
        ),
    ]
