# Generated by Django 5.1 on 2024-10-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_blogs_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='category',
        ),
        migrations.AddField(
            model_name='blogs',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='app.categoryweblog'),
        ),
    ]
